import test from 'node:test';import assert from 'node:assert/strict';
import {authorizeLoanTransition,evaluateAcceptance,personalizeVisit,validateLoanRequest,validateVisitorConsent} from '../domain/museumPolicy.js';import {adapterReadiness,requireAdapter} from '../services/adapterBoundary.js';
function loan(){return {tenantId:'t1',objectId:'OBJ-1',borrowingInstitutionId:'MUSEUM-2',startDate:'2026-09-01',endDate:'2026-10-01',conditionReportDigest:'a'.repeat(64),provenanceDecisionId:'PD-1',insuranceCertificateId:'INS-1',provenanceCleared:true,ownershipAuthorityConfirmed:true,facilityReportAccepted:true,transportPlan:{climateControl:true,securityEscort:true}};}
function consent(){return {visitorPseudonym:'visitor-hash',purpose:'visitor_experience',scopes:['interests','accessibility','language'],expiresAt:'2099-01-01T00:00:00Z',revoked:false,profile:{interests:['modern'],accessibility:['captions'],languages:['en']}};}
test('validates provenance ownership condition insurance facility dates and transport',()=>{const result=validateLoanRequest(loan());assert.equal(result.ok,true);assert.match(result.evidenceDigest,/^[a-f0-9]{64}$/);});
test('rejects unsafe or unsupported loan requests with all failures',()=>{const invalid=loan();invalid.provenanceCleared=false;invalid.ownershipAuthorityConfirmed=false;invalid.facilityReportAccepted=false;invalid.transportPlan={};invalid.endDate='2020-01-01';const result=validateLoanRequest(invalid);assert.equal(result.ok,false);assert.equal(result.errors.length,5);});
test('loan approval requires registrar and conservator evidence',()=>{const one=[{approvalRole:'registrar',decision:'approve'}];assert.equal(authorizeLoanTransition({current:'approval_pending',next:'approved',actor:{role:'approver'},approvals:one}).ok,false);const both=[...one,{approvalRole:'conservator',decision:'approve'}];assert.equal(authorizeLoanTransition({current:'approval_pending',next:'approved',actor:{role:'approver'},approvals:both}).ok,true);});
test('custody movement requires adapters and condition evidence while closure requires receipts',()=>{assert.equal(authorizeLoanTransition({current:'approved',next:'packed',actor:{role:'registrar'},adaptersReady:false,evidence:{conditionDigest:'x'}}).ok,false);assert.equal(authorizeLoanTransition({current:'approved',next:'packed',actor:{role:'registrar'},adaptersReady:true,evidence:{conditionDigest:'x'}}).ok,true);assert.equal(authorizeLoanTransition({current:'return_inspection',next:'closed',actor:{role:'auditor'},evidence:{returnConditionDigest:'x',custodyReceipt:'y'}}).ok,true);});
test('accepts minimal explicit visitor consent with expiry',()=>{const result=validateVisitorConsent(consent());assert.equal(result.ok,true);assert.match(result.consentDigest,/^[a-f0-9]{64}$/);});
test('rejects protected traits, invalid scopes, expiry, and revocation',()=>{const invalid=consent();invalid.scopes=['location'];invalid.expiresAt='2020-01-01T00:00:00Z';invalid.revoked=true;invalid.profile={religion:'x'};const result=validateVisitorConsent(invalid);assert.equal(result.ok,false);assert.equal(result.errors.length,4);});
test('personalization is deterministic explained and never automatic',()=>{const input={consent:consent(),catalogVersion:'catalog-v2',exhibits:[{id:'b',tags:['modern'],accessibility:[],languages:['en']},{id:'a',tags:['modern'],accessibility:['captions'],languages:['en']}]};const first=personalizeVisit(input),second=personalizeVisit(input);assert.deepEqual(first,second);assert.deepEqual(first.recommendations.map((item)=>item.exhibitId),['a','b']);assert.equal(first.automaticallyActioned,false);});
test('personalization fails closed without valid consent or a versioned catalog',()=>{const invalid=consent();invalid.revoked=true;assert.throws(()=>personalizeVisit({consent:invalid,catalogVersion:'v1',exhibits:[]}),/revoked/);assert.throws(()=>personalizeVisit({consent:consent(),exhibits:[]}),/versioned exhibit/);});
test('acceptance metrics cover correctness edge failures latency and real outcomes',()=>{const result=evaluateAcceptance([{correct:true,failureInjected:true,recovered:true,latencyMs:10,outcomeMet:true},{correct:false,failureInjected:false,recovered:false,latencyMs:20,outcomeMet:false}]);assert.deepEqual(result,{sampleCount:2,correctness:.5,failureRecovery:1,latencyP95Ms:20,realWorldOutcomeRate:.5});});
test('authoritative adapters fail closed until fully configured',()=>{assert.equal(adapterReadiness({}).ready,false);assert.throws(()=>requireAdapter('shipping',{}),/not ready/);const env={};for(const name of ['COLLECTIONS','CONSERVATION','INSURANCE','SHIPPING','SECURITY','CRM','TICKETING','WEBHOOKS']){env[`${name}_ADAPTER_ENABLED`]='true';env[`${name}_ADAPTER_URL`]=`https://${name.toLowerCase()}.example.invalid`;env[`${name}_ADAPTER_TOKEN`]='runtime';}assert.equal(adapterReadiness(env).ready,true);});
