CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS organizations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES organizations(id);
CREATE TABLE IF NOT EXISTS tenant_memberships(tenant_id UUID NOT NULL REFERENCES organizations(id),user_id INTEGER NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN('registrar','curator','conservator','security','approver','auditor','admin')),active BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS governed_object_loans(
 id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),idempotency_key TEXT NOT NULL,object_id TEXT NOT NULL,borrowing_institution_id TEXT NOT NULL,
 start_date DATE NOT NULL,end_date DATE NOT NULL,status TEXT NOT NULL CHECK(status IN('requested','validated','approval_pending','approved','packed','in_transit','on_loan','return_inspection','exception','closed','rejected','cancelled')),
 revision INTEGER NOT NULL DEFAULT 1,request JSONB NOT NULL,evidence_digest CHAR(64) NOT NULL,created_by INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,idempotency_key));
CREATE INDEX IF NOT EXISTS governed_object_loans_queue_idx ON governed_object_loans(tenant_id,status,updated_at);
CREATE TABLE IF NOT EXISTS loan_approvals(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),loan_id BIGINT NOT NULL REFERENCES governed_object_loans(id),actor_id INTEGER NOT NULL REFERENCES users(id),approval_role TEXT NOT NULL CHECK(approval_role IN('registrar','conservator')),decision TEXT NOT NULL CHECK(decision IN('approve','reject')),attestation_digest CHAR(64) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,loan_id,actor_id));
CREATE TABLE IF NOT EXISTS museum_operation_events(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),aggregate_type TEXT NOT NULL,aggregate_id BIGINT NOT NULL,actor_id INTEGER REFERENCES users(id),event_type TEXT NOT NULL,from_status TEXT,to_status TEXT,payload JSONB NOT NULL DEFAULT '{}'::jsonb,evidence_digest CHAR(64),occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE OR REPLACE FUNCTION prevent_museum_event_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'museum provenance is append-only'; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS museum_events_append_only ON museum_operation_events;
CREATE TRIGGER museum_events_append_only BEFORE UPDATE OR DELETE ON museum_operation_events FOR EACH ROW EXECUTE FUNCTION prevent_museum_event_mutation();
CREATE TABLE IF NOT EXISTS museum_integration_outbox(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),aggregate_type TEXT NOT NULL,aggregate_id BIGINT NOT NULL,event_type TEXT NOT NULL,payload JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','processing','delivered','dead_letter')),attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS museum_outbox_delivery_idx ON museum_integration_outbox(status,next_attempt_at);
CREATE TABLE IF NOT EXISTS museum_integration_failures(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),aggregate_type TEXT NOT NULL,aggregate_id BIGINT,adapter TEXT NOT NULL,operation TEXT NOT NULL,retryable BOOLEAN NOT NULL,error_code TEXT NOT NULL,sanitized_detail TEXT,occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS visitor_consents(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),visitor_pseudonym TEXT NOT NULL,purpose TEXT NOT NULL,scopes JSONB NOT NULL,profile JSONB NOT NULL DEFAULT '{}'::jsonb,consent_digest CHAR(64) NOT NULL,expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ,created_by INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,visitor_pseudonym,consent_digest));
CREATE TABLE IF NOT EXISTS visitor_experience_recommendations(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),consent_id BIGINT NOT NULL REFERENCES visitor_consents(id),catalog_version TEXT NOT NULL,catalog_digest CHAR(64) NOT NULL,recommendations JSONB NOT NULL,evidence_digest CHAR(64) NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','approved','delivered','expired')),created_by INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS museum_acceptance_evaluations(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),fixture_version TEXT NOT NULL,workflow TEXT NOT NULL,metrics JSONB NOT NULL,evidence_digest CHAR(64) NOT NULL,evaluated_by INTEGER NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
